//! Emit a matching `netix-republisher` `config.toml` from a simulator config.
//!
//! The simulator assigns BACnet device instances and per-object-type instance
//! numbers deterministically (see [`SimulatorConfig::expand`]). A republisher
//! that polls the simulator needs those exact addresses. Rather than have an
//! operator re-enter ~hundreds of points by hand (or hope a hand-written map
//! stays in sync), this module walks the *expanded* model and emits a ready
//! republisher config: one `[[points]]` per served BACnet object, addressed by
//! `(device_instance, object_type, object_instance)`, with `device_key` = the
//! instance's `name_prefix` and `tag_path` = the point label.
//!
//! It emits `payload_format = "netix_envelope"`, so the republisher publishes
//! `{"reason","time","id","points":[{"pointName","data","status"}]}` per device
//! to `<device_topic_prefix>/<id>/telemetry` — the shape platform MQTT workers
//! ingest.

use std::collections::HashMap;

use proto_api::base_key;
use republish_core::defaults;

use crate::config::{ConfigError, SimulatorConfig};

/// Minimal TOML basic-string escaping for the identifiers we emit.
fn toml_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Build a republisher `config.toml` (as a string) from `config`.
///
/// `mqtt_host` is written verbatim as the broker host; pass the platform MQTT
/// ingress reachable from wherever the republisher runs.
pub fn emit_republisher_config(
    config: &SimulatorConfig,
    mqtt_host: &str,
) -> Result<String, ConfigError> {
    let devices = config.expand()?;

    // A name_prefix shared by several devices (count > 1) can't be a unique
    // envelope id; fall back to the full device name for those.
    let mut key_counts: HashMap<&str, usize> = HashMap::new();
    for device in &devices {
        *key_counts.entry(base_key(&device.name)).or_insert(0) += 1;
    }

    let point_total: usize = devices.iter().map(|d| d.points.len()).sum();

    let mut out = String::new();
    out.push_str(
        "# GENERATED by `simulator --emit-republisher-config` — do not edit by hand.\n\
         # Regenerate whenever the simulator config changes so BACnet addresses stay in sync.\n\n",
    );
    out.push_str("version = 2\n");
    out.push_str("protocol = \"bacnet\"\n");
    // Provenance marker: the checksum of the simulator config this file was
    // emitted from. A loader (`AppConfig::check_sim_config_drift`) compares it
    // against the current simulator config's checksum to detect drift — the sim
    // config changed but this file was never regenerated, so its addresses are
    // stale. Top-level key, so it must precede every `[table]` below.
    out.push_str(&format!(
        "sim_config_checksum = \"{}\"\n\n",
        toml_escape(&config.checksum()?)
    ));

    out.push_str("[connections.bacnet]\n");
    out.push_str("discover_all_interfaces = true\n");
    out.push_str("port = 0\n");
    out.push_str("broadcast_address = \"255.255.255.255\"\n");
    out.push_str("discovery_window_ms = 3000\n");
    out.push_str("apdu_timeout_ms = 2000\n");
    out.push_str("poll_concurrency = 8\n");
    out.push_str("device_backoff_max_secs = 300\n");
    out.push_str("bind_failure_policy = \"skip\"\n\n");

    // Every value below comes from the SAME shared defaults the config struct
    // uses (`republish_core::defaults`), so the emitted config can never diverge
    // from the built-in struct defaults.
    out.push_str("[mqtt]\n");
    out.push_str(&format!("host = \"{}\"\n", toml_escape(mqtt_host)));
    out.push_str(&format!("port = {}\n", defaults::MQTT_PORT));
    out.push_str(&format!("use_tls = {}\n", defaults::USE_TLS));
    // Per-instance-unique id so two republishers can't kick each other off the broker.
    out.push_str(&format!(
        "client_id = \"{}\"\n",
        toml_escape(&defaults::generate_client_id())
    ));
    out.push_str("topic_prefix = \"Netix/Site\"\n");
    out.push_str("health_topic = \"Netix/Site/_health/republisher\"\n");
    out.push_str(&format!(
        "payload_format = \"{}\"\n",
        defaults::PAYLOAD_FORMAT.as_config_token()
    ));
    out.push_str(&format!(
        "device_topic_prefix = \"{}\"\n",
        toml_escape(defaults::DEVICE_TOPIC_PREFIX)
    ));
    out.push_str("retain = false\n");
    out.push_str(&format!(
        "keep_alive_secs = {}\n",
        defaults::KEEP_ALIVE_SECS
    ));
    out.push_str(&format!("autostart = {}\n\n", defaults::AUTOSTART));

    out.push_str(&format!(
        "# {point_total} points across {} devices.\n\n",
        devices.len()
    ));

    for device in &devices {
        let key = base_key(&device.name);
        let device_key = if key_counts.get(key).copied().unwrap_or(0) > 1 {
            device.name.clone()
        } else {
            key.to_string()
        };
        for point in &device.points {
            out.push_str("[[points]]\n");
            out.push_str("enabled = true\n");
            out.push_str(&format!("device_key = \"{}\"\n", toml_escape(&device_key)));
            out.push_str(&format!("tag_path = \"{}\"\n", toml_escape(&point.label)));
            out.push_str(&format!(
                "poll_interval_secs = {}\n\n",
                defaults::POLL_INTERVAL_SECS
            ));
            out.push_str("[points.addressing]\n");
            out.push_str(&format!("device_instance = {}\n", device.device_id));
            out.push_str(&format!(
                "object_type = \"{}\"\n",
                toml_escape(&point.object_type)
            ));
            out.push_str(&format!("object_instance = {}\n", point.instance));
            out.push_str("property = \"present_value\"\n\n");
        }
    }

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{
        AssetInstanceSpec, AssetTemplate, BuildingConfig, IdPolicy, SeasonalityConfig,
        SimulatorConfig, TemplatePointSpec, WeeklySchedule,
    };
    use crate::simulation::profiles::ProfileSpec;
    use std::collections::HashMap;

    fn config() -> SimulatorConfig {
        let mut templates = HashMap::new();
        templates.insert(
            "ahu".to_string(),
            AssetTemplate {
                description: "FAHU".into(),
                points: vec![
                    TemplatePointSpec {
                        label: "discharge-air-temp".into(),
                        object_type: "analog_input".into(),
                        units: Some("degrees_celsius".into()),
                        profile: ProfileSpec::Constant { value: 14.0 },
                    },
                    TemplatePointSpec {
                        label: "supply-fan-run-status".into(),
                        object_type: "binary_input".into(),
                        units: None,
                        profile: ProfileSpec::ConstantBool { value: true },
                    },
                ],
            },
        );
        SimulatorConfig {
            building: BuildingConfig {
                name: "demo".into(),
                location: None,
                timezone: None,
            },
            seasonality: SeasonalityConfig {
                weekly_schedule: WeeklySchedule {
                    weekday_occupancy: vec![],
                    weekend_occupancy: vec![],
                },
            },
            id_policy: IdPolicy {
                device_id_base: 10000,
                per_template_block: 100,
            },
            templates,
            instances: vec![AssetInstanceSpec {
                template: "ahu".into(),
                name_prefix: "ahu-12".into(),
                zone: None,
                count: 1,
            }],
            protocols: vec![],
        }
    }

    #[test]
    fn base_key_strips_instance_suffix() {
        assert_eq!(base_key("ahu-12-001"), "ahu-12");
        assert_eq!(base_key("201-001"), "201");
        assert_eq!(
            base_key("demo-weather-station-01-001"),
            "demo-weather-station-01"
        );
        assert_eq!(base_key("plain"), "plain");
    }

    #[test]
    fn emits_envelope_points_with_addressing() {
        let toml = emit_republisher_config(&config(), "mqtt.example").unwrap();
        assert!(toml.contains("payload_format = \"netix_envelope\""));
        assert!(toml.contains("device_topic_prefix = \"/Netix/Sim/Device\""));
        assert!(toml.contains("host = \"mqtt.example\""));
        // Emitted MQTT settings come from the shared defaults, so they match the
        // config struct defaults exactly (no emit-vs-struct divergence).
        assert!(toml.contains(&format!("port = {}", defaults::MQTT_PORT)));
        assert!(toml.contains(&format!("use_tls = {}", defaults::USE_TLS)));
        assert!(toml.contains(&format!("keep_alive_secs = {}", defaults::KEEP_ALIVE_SECS)));
        assert!(toml.contains(&format!(
            "poll_interval_secs = {}",
            defaults::POLL_INTERVAL_SECS
        )));
        // autostart defaults OFF (safety) — the operator starts deliberately.
        assert!(toml.contains(&format!("autostart = {}", defaults::AUTOSTART)));
        // Per-instance-unique, prefixed client id (not the old shared constant).
        assert!(toml.contains(&format!("client_id = \"{}", defaults::CLIENT_ID_PREFIX)));
        assert!(!toml.contains("client_id = \"netix-republisher\""));
        // count==1 instance -> device_key is the bare tag_identifier.
        assert!(toml.contains("device_key = \"ahu-12\""));
        assert!(toml.contains("tag_path = \"discharge-air-temp\""));
        assert!(toml.contains("tag_path = \"supply-fan-run-status\""));
        // first device block start = base + 1*block = 10100.
        assert!(toml.contains("device_instance = 10100"));
        assert!(toml.contains("object_type = \"binary_input\""));
        // one addressing table per point.
        assert_eq!(toml.matches("[[points]]").count(), 2);
        assert_eq!(toml.matches("[points.addressing]").count(), 2);
    }

    #[test]
    fn duplicate_base_key_falls_back_to_full_device_name() {
        // count == 2 -> instance names "ahu-12-001" and "ahu-12-002" both strip to
        // the same base_key "ahu-12", which therefore can't be a unique envelope id.
        // The emitter must fall back to the full device name for the device_key.
        let mut cfg = config();
        cfg.instances[0].count = 2;
        let toml = emit_republisher_config(&cfg, "mqtt.example").unwrap();
        assert!(
            toml.contains("device_key = \"ahu-12-001\""),
            "device_key must fall back to the full name, got:\n{toml}"
        );
        assert!(toml.contains("device_key = \"ahu-12-002\""));
        // The bare (colliding) base_key must NOT be emitted as a device_key.
        assert!(
            !toml.contains("device_key = \"ahu-12\""),
            "collapsing base_key must not be used as device_key when it is shared"
        );
    }

    #[test]
    fn emits_sim_config_checksum_that_round_trips_and_detects_drift() {
        use republish_core::config::AppConfig;

        let cfg = config();
        let toml = emit_republisher_config(&cfg, "mqtt.example").unwrap();

        // The emitted config carries the provenance checksum of the sim config.
        let expected = cfg.checksum().unwrap();
        assert!(
            toml.contains(&format!("sim_config_checksum = \"{expected}\"")),
            "emitted toml must stamp the sim_config_checksum, got:\n{toml}"
        );
        // Canonical hashing is deterministic across calls.
        assert_eq!(expected, cfg.checksum().unwrap());

        // A loader parses the marker and finds no drift against the same config.
        let loaded: AppConfig = toml::from_str(&toml).unwrap();
        assert_eq!(loaded.sim_config_checksum(), Some(expected.as_str()));
        assert_eq!(loaded.check_sim_config_drift(&expected), None);

        // Mutate the sim config -> its checksum changes -> drift is detected.
        let mut drifted = cfg.clone();
        drifted.instances[0].count = 3;
        let new_checksum = drifted.checksum().unwrap();
        assert_ne!(new_checksum, expected);
        assert!(
            loaded.check_sim_config_drift(&new_checksum).is_some(),
            "a changed sim config must be flagged as drift"
        );
    }
}
